aws-amplify/amplify-codegen

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
fix #21 
Add the model name to query field to prevent ambiguity when referring to field names from multiple models
```Java
public final class Blog implements Model {
public static final QueryField ID = field("Blog", "id");  //used to be 'field("id")'
//...
}
```
`jest java-visitor`
> fix(modelgen-android): add additional param to query fields

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/scalars/index.ts
re https://github.com/aws-amplify/amplify-android/issues/1164
Change the `Float` scalar type mapping to `Double` in Java modelgen. More details: https://github.com/aws-amplify/amplify-cli/pull/6145
`jest java-visitor`
> fix(modelgen-java): change float type mapping to double

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
*Issue #, if available:*
Given a basic schema in a JavaScript project:
```graphql
type Post @model {
id: ID!
title: String
}
```
after running `amplify models codegen` for the first time, the `schema.js` file is populated as expected with a unique `version` hash based on the type and the fields.
However, after changing `title` to be required with `String!`, and then running `amplify models codegen` again, the `version` doesn't change.
The same behavior also applies when changing a field from `String` to `[String]`.
My expectation is that a field's `isNullable` & `isList` attribute should be considered in this hash.
*Description of changes:*
- include `isNullable` & `isList` when calculating the `version` hash.
- tested locally with a sample app as described …
> fix(amplify-codegen-appsync-model-plugin): include isNullable & isList in version hash

- packages/graphql-types-generator/src/angular/index.ts
- packages/graphql-types-generator/test/angular/__snapshots__/index.js.snap
- packages/graphql-types-generator/test/angular/index.js
- packages/graphql-types-generator/test/fixtures/misc/subscriptionSchemaWithParameters.graphql
fix #31
The generated subscription code in angular service enable passing the parameters.
*In case of breaking customers' app, we remain the same output if no parameters are passed in schema definition.
Given a schema and sub operation as followings
**schema.graphql**
```GraphQL
type Restaurant {
id: ID!
name: String!
description: String!
city: String!
owner: String
createdAt: AWSDateTime!
updatedAt: AWSDateTime!
}
type Subscription {
onCreateRestaurant(owner: String!): Restaurant @aws_subscribe(mutations: ["createRestaurant"])
onUpdateRestaurant(owner: String!): Restaurant @aws_subscribe(mutations: ["updateRestaurant"])
onDeleteRestaurant(owner: String!): Restaurant @aws_subscribe(mutations: ["deleteRestaurant"])
}
``` …
> fix(typegen): enable passing parameters to generated subscription in Angular

- packages/graphql-types-generator/src/utilities/complextypes.ts
- packages/graphql-types-generator/test/complexTypes.ts
#52 
These changes fix the issue with swift types generation where conformance to `AWSS3InputObjectProtocol` extension was generated even when the `localUri` and `mimeType` fields are either optional or not present in the schema S3Object. This caused build errors for iOS projects. 
unit test included for changes, run using `jest`
> TypeGen(swift): Generate S3ObjectInput related extensions only if all required fields are present

- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/utils/getGraphQLDocPath.js
- packages/amplify-codegen/tests/utils/getGraphQLDocPath.test.js
The wrong type casting of `includePattern` results in failing push in Windows OS
Hot fix from https://github.com/aws-amplify/amplify-cli/pull/6722
`jest`
> fix(amplify-codegen): use correct array type for includePattern

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts
*Issue #, if available:*
https://github.com/aws-amplify/amplify-js/issues/6560
Adding the same change to JS as was added to iOS in [this PR](https://github.com/aws-amplify/amplify-cli/pull/6031/files#diff-6afc42087dd9ca87a26c81fe25d4b97f27a677500dbdb95ca19c5db8d090c637R250)
> fix(@aws-amplify/appsync-modelgen-plugin): JS targetName for hasOne

- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/src/commands/types.js
The `FeatureFlags.getBoolean` method was used at the top level in types and statements generator commands. This will break because the Feature Flags are not yet initialized. 
Moving these Feature Flag calls next to where they are required i.e inside the `generateTypes` and `generateStatements` methods.
local unit testing
> Move top level Feature Flag instance calls into the generate Methods

- package.json
- packages/amplify-codegen/package.json
For plugin packages in Node, it is recommended to specify the upstream dependencies on host packages as `peerDependencies` so they do not end up getting their own local versions of those host dependencies in their `node_modules`. 
tested locally by installing beta amplify CLI
> fix(amplify-codegen): move upstream CLI dependencies as peerDependencies

- package.json
- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/src/commands/types.js
Moved the cli-core and transformer-core dependencies as `peerDependencies` as they should be available with the host `Amplify CLI`.
tested with beta CLI version locally
> Fix the dependency issue with respect to upstream CLI packages 

- FeatureFlags.md
Adds a guide to better explain the package migration related Feature Flags.
https://docs.amplify.aws/cli/reference/feature-flags#codegen
> feat(documentation): add a guide to migration related Feature Flags

- packages/amplify-codegen/src/commands/statements.js
- packages/graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
- packages/graphql-docs-generator/__integration__/e2e.test.ts
- packages/graphql-docs-generator/__tests__/generator/generateAllOperations.test.ts
- packages/graphql-docs-generator/fixtures/caseTypes.graphql
- packages/graphql-docs-generator/src/cli.ts
- packages/graphql-docs-generator/src/generator/generateAllOperations.ts
- packages/graphql-docs-generator/src/generator/index.ts
- packages/graphql-docs-generator/src/generator/types.ts
- packages/graphql-docs-generator/src/index.ts
- packages/graphql-docs-generator/templates/_renderToVariable.hbs
_Issue #, if available:_   #37
This changes brings more uniformity to the names of operations and variables generated as parts of statements generation during `amplify codegen statements`. It takes into account various cases possible for naming graphQL types and retains them in the generated operation names. 
This would allow developers to programmatically reference operation names as described in this customer issue #37.
Added unit tests and e2e tests for all codegen target platforms.
> fix(docsgen):handling different case types

- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/tests/commands/models.test.js
_Issue #, if available:_.  #75 
These changes enable developers to organize their GraphQL schema files in nested directories eliminating the hard constraint to have all schema files at the root of `schema` folder. 
Note:
If the developer however, also has a `schema.graphql` file in the path as specified in prompt `Edit your schema at project/typescriptapp/amplify/backend/api/typescriptapp/schema.graphql or place .graphql files in a directory at project/typescriptapp/amplify/backend/api/typescriptapp/schema`, that takes precedence and the `schema` folder is not searched. 
- using unit tests
- using sample typescript and flutter apps
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> feat(modelgen): fetch graphql schemas from nested input folder

- packages/amplify-codegen/src/commands/models.js
fix #103
The syntax error is printed in a readable way.
`amplify-dev codegen models`
> fix(amplify-codegen): print syntax error in a readable output

- packages/amplify-codegen/src/commands/models.js
_Issue #, if available:_  https://github.com/aws-amplify/amplify-cli/issues/6868
This PR rollsback the `cleanGeneratedModels` Feature. 
using a sample app
> fix(amplify-codegen): disable cleanGeneratedModels Feature 

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
fix #108
Change the naming pattern for classType from `${model_name}Type` to `_${model_name}ModelType` to avoid conflicts which cause compile error.
`yarn test`
> feat(dart-modelgen): change the naming pattern for classType

- packages/amplify-codegen/src/commands/generateStatementsAndType.js
- packages/amplify-codegen/src/constants.js
- packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js
fix #121
Change the error message for api metadata not found scenario in case of confusing users.
`yarn test`
> fix(amplify-codegen): have correct error msg for api meta not found

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
_Issue #, if available:_     #42
_Description of changes:_ 
These changes add a validation step to the GraphQL schema to throw error if any model is specified without a `id: ID!` field. 
These discussion comments: [customer's comment](https://github.com/aws-amplify/amplify-codegen/issues/42#issuecomment-616865432) and [our reply](https://github.com/aws-amplify/amplify-codegen/issues/42#issuecomment-616874233), point to a need for such validation step. 
We would not generate `id` fields if the schema does not have one and through the error message point the user to the model that is missing `id: ID!` field. This is a current constraint for DataStore as it requires this field as noted [here](https://github.com/aws-amplify/amplify-codegen/issues/42#issuecomment-592279776).
_How are these …
> fix(modelgen): throw error when id field is not present on models

- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/tests/commands/models.test.js
_Issue #, if available:
fix #90
These changes add the Amplify CLI and Codegen versions used to generate the Datastore Model files as a comment. 
```
// Generated using amplify-cli-version: <version>, amplify-codegen-version: <version>
```
Since all the currently supported language targets (Swift, JS, TS, Java and Dart) use `//` for in-line comments, we did not have to customize the behavior for any specific visitor and handled the version generation in the top level `amplify-codegen` plugin package. 
Most popular programming languages support `//` for in-line comments. [Refer for overview](https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)#Inline_comments).
The implementation might evolve in the future as we support languages which do not …
> feat(amplify-codegen): Add Amplify CLI version as a comment for the Modelgen output files

- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/tests/commands/models.test.js
…ent for the Modelgen output files" (#131)
> fix: Revert "feat(amplify-codegen): Add Amplify CLI version as a comment for the Modelgen output files" (#131)

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Reverts the changes in https://github.com/aws-amplify/amplify-codegen/pull/120 to continue supporting autogeneration of ID fields for existing customers. 
Tested using iOS sample app with a model not having ID field and verified that it adds the ID field in output models. 
> fix(modelgen): revert not adding ID field automatically

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
We released a feature with modelgen version `1.23.0` that prevents auto-generation of `ID` fields if they are not present in the models. This is being reverted to continue supporting these models for existing customers. 
tested using iOS sample app
> Release: Fix modelgen failure for existing models without ID fields

- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/__snapshots__/remove-codegen.test.ts.snap
- packages/amplify-codegen-e2e-tests/src/__tests__/remove-codegen.test.ts
Adding e2e tests that cover P0 cases for the `amplify codegen remove` workflow.
Tested the test suite locally using `jest remove-codegen.test.ts` with amplify binary `4.49.0`.
> Add e2e tests for Codegen remove workflow

- CONTRIBUTING.md
- package.json
The changes enable developers to use `amplify-dev` directly for local testing by just one command `yarn setup-dev`. The cli binary in `node_modules` can also be used for local amplify e2e tests.
- Add `@aws-amplify/cli` with caret version(latest) as the dev-dependency.
- Remove additional dependencies(cli-core, graphql-core) since they are already included in cli.
- Add scripts to hoist cli package in `node_modules` so that it can scan the related plugins successfully.
- Add scripts to link `amplify-dev` to yarn global
- `yarn setup-dev` and run `amplify-dev -v`
- Run `amplify-dev codegen [subcommands]` to make sure it runs successfully and reflects local changes.
By submitting this pull request, I confirm …
> chore: optimize local testing of amplify-dev

- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/languages/swift-declaration-block.ts
- packages/appsync-modelgen-plugin/src/scalars/supported-directives.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
fix #112 
Add timestamps fields `createdAt` and `updatedAt` as read-only fields in codegen output for graphql types with `@model`. This is achieved by adding a new metadata `isReadOnly: boolean` in `CodeGenField`. This change is applied to all platforms except for flutter.
The feature will be released behind a feature flag of CLI. Refer https://github.com/aws-amplify/amplify-cli/pull/7273
```TypeScript
export type CodeGenField = TypeInfo & {
name: string;
directives: CodeGenDirectives;
connectionInfo?: CodeGenFieldConnection;
isReadOnly?: boolean // ---> new metadata
};
```
Related PR from libraries:
Android : https://github.com/aws-amplify/amplify-android/pull/1249
iOS: https://github.com/aws-amplify/amplify-ios/pull/1133
Since they are …
> feat(modelgen): add timestamp fields createdAt & updatedAt for @model

- packages/amplify-codegen/commands/codegen/codegen.js
_Issue #, if available:_ https://github.com/aws-amplify/docs/issues/2720
Previously, users could execute the `amplify codegen` command with a `--max-depth` flag. Accordingly, when users would run `amplify codegen --help` the above usage would be described. However, at some point in 2019, the above flag was changed to `--maxDepth` (see https://github.com/aws-amplify/amplify-cli/pull/2175). To date, neither the CLI help nor the official documentation reflect this change. 
This PR addresses the CLI help output. 
> fix(amplify-codegen): Correct cli help re: codegen `--maxDepth` flag

- .circleci/config.base.yml
- .circleci/config.yml
- .circleci/local_publish_helpers.sh
- package.json
- packages/amplify-codegen-e2e-core/src/utils/graphql-config-helper.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/configure-codegen.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/test-setup.ts
- scripts/split-e2e-tests.ts
Adding scripts for splitting e2e tests into individual circleCI jobs so that they can be run in parallel.
- There are 7 regions(buckets) for integration test usage with a concurrency of 4 in each region(in total 28 parallel jobs)
- Use greedy algorithm to reduce the total time of test suites
- Add new job `publish-to-verdaccio` and relevant changes to publishing scripts
> test: add split e2e test script

- packages/graphql-types-generator/src/typescript/codeGeneration.ts
- packages/graphql-types-generator/test/angular/__snapshots__/index.js.snap
- packages/graphql-types-generator/test/typescript/__snapshots__/codeGeneration.js.snap
fix #147 
fix #149 
fix #152
The PR is to fix the inconsistent type bugs introduced by a previous change https://github.com/aws-amplify/amplify-cli/pull/3324
- fix the bug of adding question mark for non-nullable fields
- add correct type declaration(`classType || null`) for nullable non-model type
> fix(graphql-types-generator): correct required types and inconsistent types

- packages/amplify-codegen/src/constants.js
- packages/amplify-codegen/src/walkthrough/questions/languageTarget.js
- packages/amplify-codegen/tests/commands/generateStatementsAndTypes.test.js
- packages/amplify-codegen/tests/walkthrough/questions/languageTarget.test.js
fix #137 
Add correct error messaging for flutter frontend which informs that flutter only supports `amplify codegen models` but other codegen commands.
- `yarn test` for unit testing
- `amplify-dev codegen add/configure` for integration testing with CLI
> fix(amplify-codegen): add correct error msg for flutter codegen

- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
Re #173 
`yarn test` and `amplify-dev codegen models` in an amplify ios app
> fix(appsync-modelgen-plugin): restore the old init if timestamp disabled

- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/src/preset.ts
Skip the types for `Query` `Mutation` and `Subscription` when processing the preset of modelgen
fix #158 
`amplify-dev codegen models` in amplify ios, android, js and flutter app
> fix(appsync-modelgen-plugin): skip query/mutation/sub types

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
Adds a null check before accessing `serializedData` in the `fromJson` method. 
refer unit test snapshots
> fix(appsync-modelgen-plugin): changes to `fromJson` method

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/languages/typescript-declaration-block.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
This allows us to omit the readonly fields (only if the `config.isTimestampFieldsAdded` flag is enabled in the `cli.json` within a user's project) from being suggested by Intellisense. The associated tests were updated automatically via running `jest --updateSnapshot`.
**_Additionally_**, I've extended the `typescript-declaration-block.ts` file with a new method to dynamically generate `type` blocks which get output in the `index.d.ts` file in user projects. I'm updating the `types.ts` in JS Datastore to reflect this new second parameter passed in to the constructor/copyOf (as seen in the generated snapshots in the test file).
None
`yarn test`
> feat(appsync-modelgen-plugin): expose readonly labels to model ts output

- .eslintrc.js
- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/languages/java-declaration-block.ts
- packages/appsync-modelgen-plugin/src/languages/swift-declaration-block.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Issue #, if available:
fix #104
Description of changes:
This PR fixes the bug in handling nullable lists and list components for `iOS` and `Android` platforms. 
There could be various combinations of optional lists in swift like `[String?]?, [String]?, [String?] and [String]`. These have to be generated correctly based on their graphQL definitions `[String], [String!], [String]! and [String!]!`.
Android DataStore on the other hand, does not enforce any checks for nullability of list components. So, a GraphQL field definition like `[String!]` will not be caught during runtime but throws the exception returned from Appsync server when a `null` value is present in the list. This PR includes fix to a bug related to handling the `required` list fields. 
This change will be released behind a …
> ModelGen(Swift, Java): Handle nullability of lists transparently based on the GraphQL schema specification

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
Use the old init method if no read-only fields found, which is typically for the case where explicit timestamp fields are defined and feature flag value is true (the timestamps are not read-only here)
fix #201
`yarn test`
> fix(appsync-modelgen-plugin): fix init when no read-only fields found

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
amplify-flutter [#759](https://github.com/aws-amplify/amplify-flutter/issues/759)
1.  Ran `yarn setup-dev`
2. Tested to generate model in Dart with below schema
3. Generated model should have internal constructor as below example
```graphql
type IDOnlyModel @model {
id: ID!
}
```
Generated model internal constructor
```dart
// Before the fix
const IDOnlyModel._internal({required this.id}): ;
// After the fix
const IDOnlyModel._internal({required this.id});
```
> fix(appsync-modelgen-plugin): dart model internal constructor with no internal fields

- packages/graphql-types-generator/src/angular/index.ts
- packages/graphql-types-generator/test/angular/__snapshots__/index.js.snap
Add `Subscription` type in angular type-gen and the corresponding `Pick` wrapper in subscription response
fix #207
`yarn test`
> fix(graphql-types-generator): add wrapperr for sub response in angular

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
This PR removes unnecessary null-aware operators from generated Dart models
* remove null-aware operator from toList() where already short-circuited
* update time and int scalar type lists to be cast as nullable
* specify has many element as nullable when mapping to JSON
```dart
// current generated model
Map<String, dynamic> toJson() => {
'id': id, 'todos': _todos?.map((e) => e?.toJson())?.toList(), 'name': _name
};      //                               ^          ^
// assumes element is not nullable          unnecessary due to short-circuiting
```
```dart
Map<String, dynamic> toJson() => {
'id': id, 'todos': _todos?.map((Todo? e) => e?.toJson()).toList(), 'name': _name
};
```
https://github.com/aws-amplify/amplify-flutter/issues/801
* Verified that snapshot errors caused by changes were …
> fix(appsync-modelgen-plugin): remove unnecessary null-aware operators

- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/scalars/supported-directives.ts
- packages/appsync-modelgen-plugin/src/utils/process-belongs-to.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections.ts
- packages/appsync-modelgen-plugin/src/utils/process-has-many.ts
- packages/appsync-modelgen-plugin/src/utils/process-has-one.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- packages/graphql-types-generator/src/utilities/graphql.ts
Codegen support for Amplify CLI v2 key and connection directives
Tested in https://github.com/aws-amplify/amplify-codegen/pull/237
Tested in https://github.com/aws-amplify/amplify-codegen/pull/237
> Release(appsync-modelgen-plugin): Add new primaryKey, index, hasOne, hasMany, and belongsTo directive support

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
fix #233 
Feature request issue: https://github.com/aws-amplify/amplify-flutter/issues/260
Added unit tests to test use cases:
* CustomType
* CustomType nests CustomType
* Model nests CustomType and list of CustomType
Should not expecting breaking change as CustomType is a feature addition.
----
> @HuiSF feat(appsync-dart-visior): Genearting dart class for CustomType (non-model)

- packages/amplify-codegen/src/walkthrough/questions/maxDepth.js
Change the default maximum statement depth to 3. This is required for the aggregate result union type to generate properly.
Manual test
> change default maximum statement depth to 3

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
Generate correct output for non-model type with `id` field defined. `id` is currently reserved field in model types but not in non-model types
fix #231
> fix(appsync-modelgen-plugin): non model type with id field in java

- packages/graphql-types-generator/src/typescript/codeGeneration.ts
- packages/graphql-types-generator/test/angular/__snapshots__/index.js.snap
- packages/graphql-types-generator/test/typescript/__snapshots__/codeGeneration.js.snap
The nested fragment fields now have correct typename generated
fix #236 
> fix(graphql-types-generator): correct typename for nested fragments

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- remove field from model for hasOne directive
- manually tested an datastore app with hasOne and v2 transformer
> fix(amplify-codegen): fix v2 has one process connection directive

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
This change inserts `provider` information to `AuthRule` initializer in generated Dart model classes. This changes is required to align with the multi-auth implementation in amplify-ios (https://github.com/aws-amplify/amplify-codegen/pull/184).
> feat(appsync-dart-visitor): insert auth provider info

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- ensure hasOne without fields generates the connected field in the parent object similar to hasOne with fields to create the same developer experience
- there is a cli PR for the same changes [here](https://github.com/aws-amplify/amplify-cli/pull/8679)
- `yarn test` passes
- test updated
> fix(amplify-codegen): updates hasone link location

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- Ensure `@hasOne` without fields generates the connected field in the parent object similar to hasOne with fields to create the same developer experience: https://github.com/aws-amplify/amplify-codegen/pull/284
- Reverts changes from #276 : https://github.com/aws-amplify/amplify-codegen/pull/281
Tested in linked PRs
> Release Codegen: @hasOne directive related fix

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-index.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/utils/process-primary-key.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/fieldUtils.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections.ts
- packages/appsync-modelgen-plugin/src/utils/process-index.ts
- packages/appsync-modelgen-plugin/src/utils/process-primary-key.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Maps new @index and @primaryKey directives back to their equivalent key representations to ensure the key attributes are not lost during the field pruning that happens when parsing connections.
The important chunks of logic are in `process-index.ts` and `process-primary-key.ts`. In these files, we look through all the fields on the model and if we find an `@index` or `@primaryKey`, respectively, we translate that into a "key" directive and attach it to the model. This allows other downstream codegen components to generate keys as they always have.
Added unit tests and verified the v2 codegen output of Android, iOS, JS, and Flutter are identical to the output of an equivalent v1 schema.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> fix: retain v2 indexes in codegen

- packages/amplify-codegen/awsAppSyncDirectives.graphql
- packages/graphql-docs-generator/awsAppSyncDirectives.graphql
- packages/graphql-types-generator/awsAppSyncDirectives.graphql
AppSync introduced new directive to support Lambda authorizer mode. Add @aws_lambda directive to allowed directives list.
- Test with CLI
- yarn test
> fix(graphql): allow aws_lambda directive

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
When looking up the connected field of a model, if the target model had a connection directive pointing to another model sometimes that field was mistakenly selected as the connection field. This PR fixes the issue by filtering the fields on type to ensure the field type is the same as the source model type.
Manually tested and added a unit test. Also updated some existing tests and confirmed with @marcvberg that the tests were wrong and should be modified.
> fix: filter related model fields by type when resolving connection

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
fix: filter related model fields by type when resolving connection #290
- [* ] PR description included
- [* ] `yarn test` passes
- [* ] Changes are tested using sample applications for all relevant platforms (iOS/android/flutter/Javascript) that use the feature added/modified
> fix: filter related model fields by type when resolving connection #290

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
For a hasOne connection on an optional field, codegen was creating a required connection field which didn't match the optional connection field in the compiled schema. This fixes that
Unit testing and a sample flutter app which the bug was reported for
> Hasone nonnull field fix

- packages/amplify-codegen-e2e-core/src/categories/api.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/add-codegen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/env-codegen.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/pull-codegen.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/remove-codegen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/datastore-modelgen.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/push-codegen.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/key-howTo4.ts
Amplify CLI release `v6.4.0` introduced some breaking changes to the API category walkthrough.
This PR incorporates those changes into the codegen e2e test setup.
tests are run successfully on CI/CD post changes.
> Fix E2e tests by including the API category walkthrough changes

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- fix naming for many-to-many join table fields
- manual testing for iOS datastore app
- `yarn test` passes
> fix(amplify-codegen): fix name for many to many join table fields

- package.json
- packages/amplify-codegen-e2e-core/package.json
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen/package.json
The recent release of CLI has major version bump for its component packages, which codegen repo has a dev dependency. Bump the dependency to next major version so that the `amplify-dev` will not break
Related packages:
- `amplify-cli-core`: `1.x` to `2.x`
- `graphql-transformer-core`: `6.x` to `7.x`
> fix: repo dev dependencies of cli components

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections-v2.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-belongs-to.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
A remnant of the V1 transformer is removing any auto generated fields from a belongsTo type connection. This was done to patch a bug in V1 that was solved by the explicit V2 directives, so we're removing the part where any belongsTo creates a field, as well as the part where added fields from belongsTo are removed.
Running unit tests and running codegen locally
> Fix: stop unnecessarily removing fields from belongsTo models

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-index.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-index.ts
Fixes an omission from https://github.com/aws-amplify/amplify-codegen/pull/286 where indexes with a queryField did not have the queryField included when mapping to a key directive on the model
Manually verified and added unit tests
> fix: include queryField when mapping index to key

- packages/amplify-codegen-e2e-tests/schemas/modelgen/model_gen_schema_with_aws_scalars.graphql
- packages/appsync-modelgen-plugin/src/__tests__/utils/process-index.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-index.ts
Fixes an omission from #286 where indexes with a queryField did not have the queryField included when mapping to a key directive on the model, and updated E2E tests to support newly enabled v2 graphql transformer.
https://github.com/aws-amplify/amplify-cli/issues/9083
Verified manually and via e2e tests in original PR.
> release support for index queryField

- .circleci/config.base.yml
- .circleci/config.yml
Add `always` to the cleanup step after each individual job to enable it to run even if it fails
> fix(e2e): use always for cleanup job

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Reverts part of changes made in #310 where additional ID fields were getting added to many-to-many connections. 
These additional fields break the CMS in Amplify Studio.
unit tests updated
> Revert not removing the additional fields in join for many-to-many

- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Moving the removing fields out of first loop to avoid missing fields during processing
fix #320 
> fix(appsync-modelgen-plugin):remove fields in second loop

- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
This Flag is needed for Android HasMany and Belongs To explicit connects for the `associatedWith` to be set correctly to the connected model field.
unit test snapshots
> Turn on the shouldUseModelNameFieldInHasManyAndBelongsTo flag for Android

- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/tests/commands/models.test.js
_Issue #, if available:_   #90
These changes fix the backwards compatibility issue with the changes introduced in this PR: https://github.com/aws-amplify/amplify-codegen/pull/116.
Unit tests and manual testing using `amplify-dev` for iOS and typescript projects. More platforms were already tested in https://github.com/aws-amplify/amplify-codegen/pull/116.
Update: Tested on iOS, Android, TS, JS, Dart sample apps on MacOS.
> fix(amplify-codegen): Add Amplify CLI version as a comment for the Modelgen output files

- .circleci/config.base.yml
- .circleci/config.yml
Upgrade xcode version used in macos builds from 11.2.1 to 13.2.1, since 11.2.1 is now deprecated https://circleci.com/docs/2.0/testing-ios/\?\#supported-xcode-versions
N/A - Contact from Circle
Will validate via CI testing, this only impacts CircleCI configuration.
> chore: Upgrade xcode version used in macos builds from 11.2.1 to 13.2.1

- packages/amplify-codegen-e2e-tests/src/environment/env.ts
- packages/amplify-codegen-e2e-tests/src/init-special-cases/index.ts
E2E tests started failing w/ CLI version 7.6.7, looks like it's because we're waiting on a response message which isn't coming since it was renamed in https://github.com/aws-amplify/amplify-cli/pull/8573
N/A
Will validate in E2E workflow runs.
> fix: update expected messages per change to CLI https://github.com/aws-amplify/amplify-cli/pull/8573

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- packages/graphql-types-generator/package.json
Add custom primary key support for datastore modelgen
- Fixed the bug that 'id' field is auto-generated even if the different primary key is defined
- Introduced three types of primary key and being processed as model metadata
- `ManagedId`
- `OptionallyManagedId`
- `CustomId`
- Added primary key support code snippet in type declaration for Amplify JS
Related JS PR: https://github.com/aws-amplify/amplify-js/pull/9380
> feat(modelgen): Custom primary key support

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Remove the timestamp fields if it is defined `null` explicitly in `@model`.
**Example schema:**
```GraphQL
type Post @model(timestamps: null) {
id: ID!
}
```
Timestamp fields `createdAt` and `updatedAt` will not be generated, which is consistent with the `@model` transformer behavior.
> fix(modelgen): remove timestamps if defined null in @model

- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/src/__tests__/utils/process-auth.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-auth.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Use `sub` as the default identity claim value instead of `username`
> feat: use sub as default identity claim

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-javascript-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
- Fix the bug that metadata type is not correctly generated in constructor and copyOf
> fix(modelgen-js): rm readonly fields check for type metadata

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-javascript-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
- Fixed the bug that model metadata type is not generated in some cases #367 
> Release Amplify Codegen V2.27.1

- packages/amplify-codegen/package.json
Add `amplify-prompts` as dependency because of old version CLI which does not have this package will break
> fix: add amplify prompts in package.json

- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/utils/validateAmplifyFlutterCapableZeroThreeFeatures.js
- packages/amplify-codegen/tests/utils/validateAmplifyFlutterCapableForNonModel.test.js
Use `console.log` instead for error printing and remove `amplify-prompts` dependency
> fix: rm amplify-prompts and use console log

- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/src/utils/validateAmplifyFlutterCapableZeroThreeFeatures.js
- packages/amplify-codegen/src/utils/validateAmplifyFlutterCoreLibraryDependency.js
- packages/amplify-codegen/src/utils/validateAmplifyFlutterVersion.js
- packages/amplify-codegen/tests/commands/models.test.js
- packages/amplify-codegen/tests/utils/validateAmplifyFlutterCapableForNonModel.test.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/configs/dart-config.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
Context as mentioned in [this PR](https://github.com/aws-amplify/amplify-codegen/pull/380):
Changes flutter (dart) codegen so that generated models will import from amplify_core, rather than datastore. This is to support a feature in 0.4.0 amplify-flutter where API users can generate models without a datastore dependency. For this reason, the models need to import from core, as implemented here.
The codegen files here would depend on a version of amplify-flutter with the deps moved (0.4.0+). 0.4.0 will continue to export the same things from datastore to maintain compatibility with older codegen files, but the new codegen files with this change will need a newer version of amplify-flutter to correctly resolve dependencies.
These changes:
- Add a version check to determine the relevant …
> [Dart] Update imports generated for flutter datastore plugin dependency

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
Add a generator to generate `indexes` in model schema. This is an existing feature in the swift and java visitors.
* Unit tests in amplify-codegen
* Sample App testing with amplify-flutter, based on this PR https://github.com/aws-amplify/amplify-flutter/pull/1366
> feat(appsync-dart-visitor): attach index info to model schema

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
https://github.com/aws-amplify/amplify-flutter/issues/1426
Add `@override` to class methods.
> Add method override annotation

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- packages/graphql-types-generator/package.json
The following changes are made in response to https://github.com/aws-amplify/amplify-cli/pull/9580
- Add sort key fields in the joint model of `manyToMany` when they are defined in the original model
- Add the secondary key infos in joint model
- Add the sort key fields from original model in joint model secondary key sort key fields
Example GraphQL Schema
```GraphQL
type ModelA @model {
id: ID! @primaryKey(sortKeyFields: ["sortId"])
sortId: ID!
models: [ModelB] @manyToMany(relationName: "ModelAModelB")
}
type ModelB @model {
id: ID! @primaryKey(sortKeyFields: ["sortId"])
sortId: ID!
models: [ModelA] @manyToMany(relationName: "ModelAModelB")
}
```
Schema after manyToMany process
```GraphQL
type ModelA @model {
id: ID! @primaryKey(sortKeyFields: ["sortId"])
sortId: ID!
models: …
```
> feat(appsync-modelgen-plugin): add sort key field in manyToMany models

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
Change Flutter model id field name from `<modelName>.id` to just `id`.
The original behavior should be redundant and inaccurate.
1. In the [iOS implementation of amplify-flutter](https://github.com/aws-amplify/amplify-flutter/blob/5c6d8eab63c1ea11e63d1ec8e82a975a4dffeb28/packages/amplify_datastore/ios/Classes/types/query/QueryPredicateBuilder.swift#L23-L29), it removes `<modelName>` elaborately when using the field name
2. The original name breaks query predicate functionality in amplify-flutter Android
- base sync filter generated wrongly (see [this issue](https://github.com/aws-amplify/amplify-flutter/issues/1565))
- `DataStore.query` was luckily working as amplify-android generated SQL commands somehow compatible with `<modelName>.id`
**NOTE:** this change won't be a breaking change, …
> fix(appsync-dart-visitor): generate correct model id filed name

- packages/amplify-codegen-e2e-core/package.json
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen-e2e-tests/src/__tests__/feature-flags.test.ts
- packages/amplify-codegen-e2e-tests/src/amplify-app-helpers/amplify-app-setup.ts
- packages/amplify-codegen-e2e-tests/src/cleanup-e2e-resources.ts
- packages/amplify-codegen-e2e-tests/src/configure_tests.ts
- packages/amplify-codegen-e2e-tests/src/environment/env.ts
- packages/amplify-codegen-e2e-tests/src/import-helpers/expects.ts
- packages/amplify-codegen-e2e-tests/src/import-helpers/settings.ts
- packages/amplify-codegen-e2e-tests/src/import-helpers/utilities.ts
- packages/amplify-codegen-e2e-tests/src/import-helpers/walkthroughs.ts
- packages/amplify-codegen-e2e-tests/src/init-special-cases/index.ts
- packages/amplify-codegen-e2e-tests/src/plugin/index.ts
- packages/amplify-codegen-e2e-tests/src/plugin/new-plugin.ts
- packages/amplify-codegen-e2e-tests/src/plugin/verifyPluginStructure.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/authHelper.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/common.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/functionTester.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/auth-customClaims.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/auth-private2.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/auth-public1.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/auth-public2.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/auth-usingOidc.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/function-chaining.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/function-differentRegion.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/function-example2.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/key-howTo4.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/predictions-usage.ts
- packages/amplify-codegen-e2e-tests/src/schema-api-directives/tests/searchable-usage.ts
Somebody was squatting on the non-namespaced versions of our test core package, resulting in a security alert. This is a private package and should not be published. Flipping to use the secured `@aws-amplify` npm namespace to avoid issues like this in the future.
N/A
Built and tested the repo.
> chore: flip to use @aws-amplify namespace for private packages to avoid collision with improperly published packages

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-javascript-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Use optional fields for manyToMany foreign key fields. This only has impact on the JS modelgen since in native platforms FK fields are always removed.
> fix(modelgen-js): use optional fields for FK in manyToMany

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-javascript-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Hot fix for JS modelgen to use optional FK fields in manyToMany
> Release codegen 3.0.3

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-json-metadata-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts
- Used string array instead of single string for `associateWith` in JS model schema file
- Added foreign key of sort key field in `associateWith`
> fix(modelgen-js): use string array for associateWith

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
For the schema:
```
type ModelExplicitDefaultPk @model {
id: ID! @primaryKey
name: String
}
```
Improve the DX by using the default IdentifierFormat and IdentifierProtocol for when the identifier is explicitly declared as the primary key that's simply named "id". 
The DX before this change:
```swift
Amplify.DataStore.query(ModelExplicitDefaultPk.self,
byIdentifier: .identifier(id: model.id)) { result in
Amplify.DataStore.delete(ModelExplicitDefaultPk.self,
withIdentifier: .identifier(id: model.id)) { result in 
```
DX after this change:
```swift
Amplify.DataStore.query(ModelExplicitDefaultPk.self,
byIdentifier: model.id) { result in
Amplify.DataStore.delete(ModelExplicitDefaultPk.self,
withIdentifier: model.id) { result in 
```
`yarn test` and `yarn setup-dev` and then `amplify-dev …
> fix(amplify-codegen): iOS use default when PK.OptionallyManagedId

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
Related to https://github.com/aws-amplify/amplify-ios/pull/2077 this renames ModelIdentifiable.Identifier to IdentifierProtocol
Ran `yarn setup-dev` and `amplify-dev codegen models` from the sample app containing iOS CPK schemas. The app is compiling and working as expected
> fix(amplify-codegen): rename ModelIdentifiable.Identifier to identifierProtocol

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
Patch for iOS modelgen of CPK feature:
- Renamed `ModelIdentifiable.Identifier` to `IdentifierProtocol`
- iOS now treats `id: ID @primaryKey` as the default managed ID
> Release Amplify Codegen v3.0.5

- packages/amplify-codegen/src/utils/validateDartSDK.js
- packages/amplify-codegen/tests/utils/validateDartSDK.test.js
Enable the `allowPreRelease` flag for our semver check to enable capturing tagged releases correctly.
https://github.com/aws-amplify/amplify-codegen/issues/437
Added unit tests to cover the cases described in the issue which failed, then made the change and they pass.
> fix: support pre-release version tags for dart version check

- .circleci/config.yml
- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/model-introspection-codegen.test.ts
- packages/amplify-codegen/amplify-plugin.json
- packages/amplify-codegen/commands/codegen/model-introspection.js
- packages/amplify-codegen/src/commands/model-intropection.js
- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/src/index.js
- packages/amplify-codegen/tests/commands/model-introspection.test.js
- packages/appsync-modelgen-plugin/.npmignore
- packages/appsync-modelgen-plugin/package.json
- packages/appsync-modelgen-plugin/schemas/introspection/1/ModelIntrospectionSchema.json
- packages/appsync-modelgen-plugin/scripts/generateSchemas.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/interfaces/introspection/index.ts
- packages/appsync-modelgen-plugin/src/interfaces/introspection/model-schema.ts
- packages/appsync-modelgen-plugin/src/plugin.ts
- packages/appsync-modelgen-plugin/src/preset.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-model-introspection-visitor.ts
- packages/appsync-modelgen-plugin/tsconfig.json
- scripts/split-e2e-tests.ts
Add new codegen command which will generate the `model-introspection.json` file under the given directory path.
```bash
$ amplify codegen model-introspection --output-dir ${dir_path_input}
```
The changes include:
- New introspection visitor
- JSON schema and its validator
- Script for generating JSON schema from TS type definition file
- Unit and E2E tests
> feat(amplify-codegen): new codegen command of  model intropection

- .circleci/config.base.yml
- .circleci/config.yml
- .circleci/local_publish_helpers.sh
The e2e tests are now resolved to the real local version of `amplify-codegen`
- Added script to change npm global directory to give correct access for `npm install` on CI
- Removed `amplify-app` installation
- Added `npm list` to check the installed amplify CLI plugin versions
> fix(e2e): Resolve the local version codegen for e2e tests

- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-android.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-flutter.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-ios.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/datastore-modelgen.ts
- packages/amplify-codegen/src/commands/model-intropection.js
- packages/amplify-codegen/src/commands/models.js
Add support for new `--output-dir` flag when invoking models directly. The parameter is not required
N/A
> Add support for output dir arg on models

- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-android.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-flutter.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-ios.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/datastore-modelgen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/datastore-modelgen.ts
- packages/amplify-codegen/commands/codegen/models.js
- packages/amplify-codegen/src/commands/model-intropection.js
- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/src/utils/getOutputDirParam.js
- packages/amplify-codegen/tests/utils/getOutputDirParam.test.js
- packages/appsync-modelgen-plugin/src/preset.ts
`--output-dir` flag wasn't applying for `codegen models` correctly, we needed to plumb the flag all the way through, I also refactored how we detect the flag a bit to simplify the `generateModels` method a bit.
N/A
Unit tests, verified that both modelgen and model-introspection e2e tests are passing now.
> fix: simplify outputDirParam handling, and plumb through to models

- package.json
- packages/amplify-codegen-e2e-core/package.json
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen/package.json
- yarn.lock
- Bumped the `amplify-cli-core` to `^3.0.0`
- Pinned `typescript` to `4.7.4` as `4.8+` causes compile error
> chore: Bump cli core to next major version

- packages/amplify-codegen/commands/codegen/models.js
- packages/amplify-codegen/src/commands/model-intropection.js
- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/src/index.js
- packages/amplify-codegen/tests/commands/model-introspection.test.js
This exposes a new method over the plugin system called `getModelIntrospection` which can be invoked from elsewhere in the CLI.
This can be invoked from a location in the CLI which has access to the context via.
```js
const modelIntrospection = await context.amplify.invokePluginMethod(
context,
'codegen',
undefined,
'getModelIntrospection',
[context],
);
```
N/A
Manually aliased this command to the `codegen model-introspection` and inspected the output.
> feat: allow model-introspection to be invoked internally to the CLI

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-javascript-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
Always import `LazyLoading` and `LazyLoadingDisabled` in TypeScript generation. 
Any schema that does not contain any relationships will result in a type declaration file for TypeScript that is invalid. This is effecting >= 10.3.1 of the CLI and >= 3.2.0 of codegen.
Minimum reproduction:
```
type Todo @model {
id: ID!
name: String!
}
```
The generated file 
```
import { ModelInit, MutableModel } from "@aws-amplify/datastore";
type EagerTodo = {
readonly id: string;
readonly name: string;
}
type LazyTodo = {
readonly id: string;
readonly name: string;
}
export declare type Todo = LazyLoading extends LazyLoadingDisabled ? EagerTodo : LazyTodo
export declare const Todo: (new (init: ModelInit<Todo>) => Todo)
```
The file is missing the lines.
```
// @ts-ignore
import { LazyLoading, …
```
> fix: lazy codegen for schemas without relationships

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-has-many.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-javascript-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-json-metadata-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-has-many.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-model-introspection-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Today, if you add a `@hasMany` directive to your schema without a corresponding `@belongsTo` on the related model, then the JS library will fail to cascade delete the related item. It appears this is because the Javascript Model Intermediate Platform Representation (MIPR) file is missing an implicit `key` in the related model.
This is being generated implicitly in the transformer today, since a DynamoDB GSI is required to query correctly, but this appears to have been missed in Codegen when the GQLv2 transformer support was launched at the end of 2021.
Because we haven't confirmed this behavior is in error on other platforms, I'm implementing this behind a boolean switch, so only the Javascript, Typescript, JSON, and Model Introspection outputs will see this change, but Flutter, Java, and …
> fix: addressing missing key for unidirectional @hasMany on JS

- CONTRIBUTING.md
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
This PR changes Dart modelgen so that instances of the model name are hardcoded rather than taken from `toString()` on the type, which is not recommended because that name will get minified in some environments (like Flutter web) https://dart.dev/tools/linter-rules#avoid_type_to_string.
Basically, models will have `'Post'` hardcoded instead of `(Post).toString()` or similar.
https://github.com/aws-amplify/amplify-flutter/issues/2330
- [x ] PR description included
- [ x] `yarn test` passes
- [ x] Tests are [changed or added](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#tests)
- [ n/a] Relevant documentation is changed or added (and PR referenced)
- [ n/a] Breaking changes to existing customers are released behind a feature flag or major version update
- [ x] …
> fix(amplify-codegen):  add hardcoded modelName to Dart

- yarn.lock
`@aws-amplify/graphql-schema-test-library` was mistakenly not added to the lock file in https://github.com/aws-amplify/amplify-codegen/pull/513. Added to the lock file by running `yarn install`.
N/A
N/A
> chore: add @aws-amplify/graphql-schema-test-library to lock file

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections-v2.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-json-metadata-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
- packages/appsync-modelgen-plugin/src/utils/process-has-one.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-model-introspection-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
When the CPK feature flag is `ON`, this change fixes the `associatedWith` fields that are generated in a Bi-Directional Has-One relationship. 
We add an option `shouldUseFieldsInAssociatedWithInHasOne` to control this change and limit it only to the Model Introspection Visitor (produces `model-introspection.json` output), JS, TS and JSON metadata vistors (linked to `schema.js` output).
Unit tests
> fix(appsync-modelgen-plugin): associatedWith fields in HasOne bi-directional with CPK enabled

- .circleci/config.base.yml
- .circleci/config.yml
- packages/amplify-codegen-e2e-core/src/init/index.ts
- packages/amplify-codegen-e2e-core/src/init/initProjectHelper.ts
- packages/amplify-codegen-e2e-core/src/init/swift.ts
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen-e2e-tests/src/__tests__/build-app-swift.test.ts
- packages/amplify-codegen-e2e-tests/test-apps/swift/.gitignore
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift.xcodeproj/project.pbxproj
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift/Assets.xcassets/AccentColor.colorset/Contents.json
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift/Assets.xcassets/AppIcon.appiconset/Contents.json
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift/Assets.xcassets/Contents.json
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift/ContentView.swift
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift/Preview Content/Preview Assets.xcassets/Contents.json
- packages/amplify-codegen-e2e-tests/test-apps/swift/swift/swiftApp.swift
- scripts/split-e2e-tests.ts
- yarn.lock
See https://github.com/aws-amplify/amplify-codegen/pull/513 for similar test for TypeScript apps.
PR to introduce the error: https://github.com/aws-amplify/amplify-codegen/pull/489
PR to fix the error: https://github.com/aws-amplify/amplify-codegen/pull/500
[Run on CircleCI](https://app.circleci.com/pipelines/github/aws-amplify/amplify-codegen/2643/workflows/92d3cc95-6956-4f8a-ae20-9235e61d940b)
> ci: add build e2e test for swift

- package.json
- yarn.lock
- Update `yarn.lock`
- Add graphql resolution which fixes the duplicate graphql module installation during local setup-dev
> chore: update yarn.lock and add graphql resolution

- .circleci/config.base.yml
- .circleci/config.yml
Removed the OS suffix for cache naming as there is a mismatch between `parameter.os` (which is a wrapped object rather than single string and its alias `l`/`w`. This causes the cache not restoring issue and the deploy job to fail.
> fix(ci): rm suffix of os in cache

- .circleci/config.base.yml
- .circleci/config.yml
- packages/amplify-codegen-e2e-core/package.json
- packages/amplify-codegen-e2e-core/src/asciinema-recorder.ts
- yarn.lock
- Update dependencies to be compatible with Node 18.
- Update the CI config to run on Node 18.
Existing tests run successfully post upgrade.
https://app.circleci.com/pipelines/github/aws-amplify/amplify-codegen/2899/workflows/2f10290a-4b85-460e-9606-a8b85a9e3e70
> Support for NodeJS v18

- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/tests/commands/statements.test.js
- packages/graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
- packages/graphql-docs-generator/__tests__/generator/getFields.test.ts
- packages/graphql-docs-generator/src/cli.ts
- packages/graphql-docs-generator/src/generator/getFields.ts
- packages/graphql-docs-generator/src/generator/types.ts
- packages/graphql-docs-generator/src/index.ts
**BREAKING CHANGE**
Add `__typename` to selection set of generated queries for object types.
[Typename Introspection](https://spec.graphql.org/June2018/#sec-Type-Name-Introspection) is included in the GraphQL spec and is accessible on the meta field `__typename`. `__typename` is available on object, interface, and union types.
This change adds `__typename` to only object types because we do not generate resolvers for interface and union types. (We could add this anyway for customers not using the transformers).
AppSync is guaranteed to supply `__typename` for all queries not using interface or union types regardless of the resolver implementation. Therefore, this change is only potential breaking for customers meeting the following criteria:
1. using a non-AppSync backend
2. the backend …
> feat: add __typename to selection set

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-index.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-index.ts
- packages/appsync-modelgen-plugin/src/utils/stringUtils.ts
Assigns a default name to index directive if source schema doesn't have one.
- This change helps codegen to detect the sortkey fields of PK correctly as codegen considers key directive without a name as PK.
Fixes https://github.com/aws-amplify/amplify-category-api/issues/1432
- Manual test
- New Unit test
> fix(codegen): generate default name for index directive

- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/tests/commands/statements.test.js
- packages/graphql-docs-generator/API.md
- packages/graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
- packages/graphql-docs-generator/__tests__/generator/getFields.test.ts
- packages/graphql-docs-generator/src/cli.ts
- packages/graphql-docs-generator/src/generator/getFields.ts
- packages/graphql-docs-generator/src/generator/types.ts
- packages/graphql-docs-generator/src/index.ts
- Revert the `__typename` change in doc generator
- Downgrade amplify codegen to version 3 to avoid version mismatch error from JS datastore
> fix: codegen downgrade to version 3

- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/tests/commands/statements.test.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-json-metadata-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts
- packages/graphql-docs-generator/API.md
- packages/graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
- packages/graphql-docs-generator/__tests__/generator/getFields.test.ts
- packages/graphql-docs-generator/src/cli.ts
- packages/graphql-docs-generator/src/generator/getFields.ts
- packages/graphql-docs-generator/src/generator/types.ts
- packages/graphql-docs-generator/src/index.ts
- Re-revert the `__typename` change
- Hard code the `codegenVersion` to `3.4.4` which is the latest version in major 3. This will act as schema version instead of codegen version. The hard code is to pass the datastore validation.
- Manually bump the `amplify-codegen` back to `4.0.0`
> chore: retain the major version 4 for codegen

- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/tests/commands/statements.test.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-json-metadata-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-json-metadata-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts
- packages/graphql-docs-generator/API.md
- packages/graphql-docs-generator/__integration__/__snapshots__/e2e.test.ts.snap
- packages/graphql-docs-generator/__tests__/generator/getFields.test.ts
- packages/graphql-docs-generator/src/cli.ts
- packages/graphql-docs-generator/src/generator/getFields.ts
- packages/graphql-docs-generator/src/generator/types.ts
- packages/graphql-docs-generator/src/index.ts
* Revert "fix: codegen downgrade to version 3 (#589)"
This reverts commit c1f9f36979691dfba3dd3db1c4a516aeeb29c41e.
* fix: use hard code codegen version in schema.js
* fix lint
> Release Amplify Codegen at major version 4

- packages/amplify-codegen-e2e-core/src/init/amplifyPull.ts
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen-e2e-tests/src/__tests__/pull-codegen.test.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/datastore-modelgen.ts
Flutter apps require a `pubspec.lock` file in their project before running modelgen as it is supported for only dart versions above `0.6.0`. This change adds that step. https://github.com/aws-amplify/amplify-codegen/pull/576
Full e2e now pass as seen from the checks
> chore: fix e2e tests related to flutter pubspec file

- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/add-codegen-js.test.ts
- packages/amplify-codegen/src/codegen-config/AmplifyCodeGenConfig.js
- packages/amplify-codegen/src/codegen-config/index.js
- packages/amplify-codegen/tests/codegen-config/index.test.js
Check if the project is initialized with Amplify before calling the `getEnvInfo` on the shared Amplify context.
This fixes the issue with running `add codegen --apiId <appsync-api-id>` command. The `apiId` input is optional.
Validated in non-amplify and amplify initialized JS applications.
Added e2e test
> Fix add codegen from a non-amplify application

- packages/amplify-codegen/package.json
- packages/appsync-modelgen-plugin/package.json
- packages/graphql-docs-generator/package.json
- packages/graphql-types-generator/package.json
Add unit test coverage thresholds (currently set to `min(curr_val, 80)`) to prevent reduction in unit test coverage.
Info on the coverage configuration can be found here https://jestjs.io/docs/27.x/configuration#coveragethreshold-object
Line coverage refers to what % of lines are covered in the given package (in average across all files, since we're using global)
Branch coverage refers to what % of code paths are covered in the given package (in average across all files, since we're using global)
Function coverage refers to what % of functions are covered in the given package (in average across all files, since we're using global)
N/A
Ran unit tests.
> chore: add unit test coverage thresholds

- packages/appsync-modelgen-plugin/package.json
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
If CPK flag is enabled:
* We will now create a T: ModelIdentifier for all models (not just cpk with sort keys)
* `resolveIdentifier` will only return the ModelIdentifier if cpk + sort key
* deprecation warning for `resolveIdentifier` as it is only intended to be used internally in Amplify
All changes are additive (non-breaking)
* Added snapshot tests for new scenarios
> feat: Add ModelIdentifier for all Java models

- .codebuild/cleanup_workflow.yml
- .codebuild/scripts/lint_pr.sh
- packages/amplify-codegen-e2e-core/src/init/initProjectHelper.ts
- packages/amplify-codegen-e2e-core/src/utils/add-ci-tags.ts
- packages/amplify-codegen-e2e-core/src/utils/index.ts
- packages/amplify-codegen-e2e-core/src/utils/pinpoint.ts
- packages/amplify-codegen-e2e-core/src/utils/sdk-calls.ts
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen-e2e-tests/src/cleanup-cb-e2e-resources.ts
- packages/amplify-codegen-e2e-tests/src/init-special-cases/index.ts
- Added resource cleanup scripts for codebuild
- Fixed the lint script so that it now can emit the lint error instead of ignore it in codebuild
Run the cleanup workflow in beta accounts
> chore: add cleanup resources script for codebuild

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-model-introspection-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Today, a key directive in GraphQLV1 that uses a belongsTo FK will cause the model introspection schema to fail. This addresses that issue, by no longer removing the field hardcoded by 'id' but instead checking if it's the model pk.
N/A - ticket
Added unit tests which previously failed, added v2 test for comparison of behavior.
> fix: support key directive in model introspection schema gen

- .codebuild/release_workflow.yml
- package.json
- yarn.lock
The API plugin depends on `4.0.4` of CLI core without a `^` today https://github.com/aws-amplify/amplify-category-api/blob/28a89d960eaf3be3b729af567c83442e374e2443/packages/amplify-category-api/package.json#L71. While the Codegen resolves to latest. This is causing the API related CLI commands to fail using the dev binary.
Also includes a typo correction in a buildpsec file.
> chore: fix FF not initialized error

- packages/amplify-codegen/src/codegen-config/index.js
- packages/amplify-codegen/tests/codegen-config/getCodegenConfig.test.js
The new API either returns a valid `maxDepth` config parameter which is set via `amplify codegen add` by the customers.
Or it returns `undefined` if any customers manually made changes to the `graphqlconfig.yml` file to remove it. This case will be handled in Studio UI by prompting customers to re-configure their codegen via `amplify codegen update` or `amplify codegen configure`.
> Add maxDepth parameter fetching via Codegen Config getter API

- .codebuild/scripts/publish.sh
- packages/amplify-codegen/package.json
- shared-scripts.sh
The codebuild job starts with HEAD at a detached commit from the `release` branch, which is observed in the SSH session. Another thing is that there is no default tracking branches for the cloned repo in the container.
Adding explicit `pull` from origin for `main` and `release` to be sure we're using latest code and the history is all fetched.
> fix: post publish sync between main and release

- .codebuild/scripts/publish.sh
- shared-scripts.sh
> build: add build packages before release

- package.json
- scripts/cloud-utils.sh
- scripts/view-test-artifacts.ts
Use the ada CLI authentication to view the E2E test artifacts. This keeps it more uniform with other scripts we have.
> chore: use ada auth for viewing e2e artifacts

- .codebuild/e2e_workflow.yml
- packages/graphql-types-generator/src/swift/appSyncCompatibilityTypes.ts
- packages/graphql-types-generator/src/swift/codeGeneration.ts
- packages/graphql-types-generator/test/swift/__snapshots__/codeGeneration.ts.snap
- packages/graphql-types-generator/test/swift/codeGeneration.ts
Currently developers that have an AppSync backend that was not provisioned with Amplify CLI can still generate the **API.swift** file from the introspection schema. This file has a hard dependency on [iOS AppSync SDK client.](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/). The top of API.swift contains `imports AWSAppSync`.
This file is pretty useful as it contains all the different operations available and  components to successfully make a request, but cannot be used with Amplify's APIPlugin. This PR makes the API.swift file compatible with Amplify AWSAPIPlugin, removing the dependency on AppSync SDK.
1. If can import AWSAPIPlugin, declare the types required to compile API.swift in-line. The required types were extracted out of AWSAppSync SDK codebase. Additionally, the Data …
> feat: API.swift compatibility with AWSAPIPlugin

- .codebuild/cleanup_e2e_resources.yml
- .codebuild/cleanup_workflow.yml
- .codebuild/run_android_modelgen_e2e_test.yml
- .codebuild/run_e2e_tests.yml
- .codebuild/run_ios_modelgen_e2e_test.yml
- package.json
- packages/amplify-codegen-e2e-core/package.json
- packages/amplify-codegen-e2e-core/src/nexpect-reporter.js
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen-e2e-tests/src/cleanup-e2e-resources.ts
- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- scripts/view-test-artifacts.sh
- scripts/view-test-artifacts.ts
- shared-scripts.sh
- yarn.lock
- Feature: swift using improved pluralization for modelgen
- Dx improvements for code build
> Release Amplify Codegen 08-15-2023

- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/commands/model-intropection.js
- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/tests/commands/model-introspection.test.js
- packages/amplify-codegen/tests/commands/models.test.js
- packages/appsync-modelgen-plugin/API.md
- packages/appsync-modelgen-plugin/src/preset.ts
- packages/graphql-generator/API.md
- packages/graphql-generator/package.json
- packages/graphql-generator/src/__tests__/__snapshots__/models.test.ts.snap
- packages/graphql-generator/src/models.ts
- packages/graphql-generator/src/typescript.ts
* Add `generateModels` to graphql-generator
* Refactor amplify-codegen to `generateModels`
N/A
* Unit tests
* E2E tests
There seems to be a gap in coverage for the `overrideOutputDir` param. I am going to add tests for this before merging to main.
> refactor: create graphql-generator entry point for models

- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/src/utils/defaultDirectiveDefinitions.js
- packages/amplify-codegen/src/utils/index.js
- packages/amplify-codegen/tests/commands/__snapshots__/models.test.js.snap
- packages/amplify-codegen/tests/commands/models.test.js
* add hard coded default directive definitions to amplify-codegen
* Use default directives if `getTransformerDirectives` fails (outside of amplify project)
N/A
* Unit testing
* E2E tests to come in later PR
> feat: use default directive definitions if outside amplify project

- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/tests/commands/model-introspection.test.js
This refactor should make the functional change to support modelgen without an amplify initialized backend a bit more straightforward, and the type annotations have helped me in the refactor. There are no functional changes, and I'm relying on unit tests to verify that fact.
N/A
Unit Tests
> chore: refactor command/models.js into independent functions, add jsdoc type annotations

- packages/amplify-codegen/src/commands/add.js
- packages/amplify-codegen/src/utils/downloadIntrospectionSchema.js
- packages/amplify-codegen/tests/commands/__snapshots__/add.test.js.snap
- packages/amplify-codegen/tests/commands/add.test.js
* download introspection schema when apiId is passed
```
amplify codegen add --apiId <api-id> --region <region>
```
When `--apiId` is set, the CLI will attempt to download the introspection schema to `./schema.json`. When no `--region` is supplied `us-east-1` is used. If the api cannot be found the CLI will prompt the customer to try a different region.
```
✖ Getting API details
AppSync API was not found in region us-east-1
? Do you want to choose a different region Yes
? Choose AWS Region (Use arrow keys)
❯ US East (N. Virginia) 
US East (Ohio) 
US West (N. California) 
US West (Oregon) 
EU (Stockholm) 
EU (Milan) 
EU (Ireland) 
(Move up and down to reveal more choices)
```
An additional change (https://github.com/aws-amplify/amplify-codegen/pull/689) is needed after this PR. The …
> fix: download introspection schema when apiId is passed

- .codebuild/e2e_workflow.yml
- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen-e2e-core/src/utils/frontend-config-helper.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-android.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-flutter.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-ios.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/index.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/uninitialized-modelgen.ts
Add per-platform e2e tests to verify that `amplify codegen models` can be invoked in a project without an amplify initialized backend locally.
N/A
E2E Tests pass
> feat: add e2e tests for modelgen in an uninitialized project

- packages/amplify-codegen/src/commands/generateStatementsAndType.js
- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/src/commands/types.js
- packages/amplify-codegen/src/utils/ensureIntrospectionSchema.js
- packages/amplify-codegen/src/utils/getAppSyncAPIInfoFromProject.js
- packages/amplify-codegen/src/utils/index.js
The customer can end in a broken state if:
1. `amplify codegen add --apiId <api-id>`
2. `rm -rf schema.json`
3. `amplify codegen`
There is no way the customer can use the codegen CLI to download the introspection schema. 
```
$ amplify-dev codegen types
⠋ Generating🛑 ENOENT: no such file or directory, open '/Users/dppilche/amplify/apps/testnoamplify/schema.json'
Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
⠹ Generating^Aborted!
```
```
$ amplify-dev codegen statements 
Cannot find GraphQL schema file: /Users/dppilche/amplify/apps/testnoamplify/schema.json
```
```
$ amplify codegen 
Please download the …
```
> fix: codegen --apiId broken state

- .codebuild/e2e_workflow.yml
- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen-e2e-core/src/utils/frontend-config-helper.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-android.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-flutter.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-ios.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-modelgen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/index.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/uninitialized-modelgen.ts
- packages/amplify-codegen/src/commands/models.js
- packages/amplify-codegen/src/utils/defaultDirectiveDefinitions.js
- packages/amplify-codegen/src/utils/getModelSchemaPathParam.js
- packages/amplify-codegen/src/utils/getOutputDirParam.js
- packages/amplify-codegen/src/utils/getProjectRoot.js
- packages/amplify-codegen/src/utils/index.js
- packages/amplify-codegen/tests/commands/__snapshots__/models.test.js.snap
- packages/amplify-codegen/tests/commands/model-introspection.test.js
- packages/amplify-codegen/tests/commands/models.test.js
- packages/amplify-codegen/tests/utils/getModelSchemaPathParam.test.js
- packages/amplify-codegen/tests/utils/getProjectRoot.test.js
Release support fro amplify codegen models without an amplify app initialized locally.
N/A
Unit + E2E Tests + Exploratory Testing with the CLI
> feat: merge noinit-modelgen into main to support executing amplify codegen models without an initialized amplify app

- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen/commands/codegen/add.js
- packages/amplify-codegen/src/utils/getAppSyncAPIInfoFromProject.js
Getting existing e2e tests passing by removing the --apiId param when not downloading a backend API.
Also fixed a minor bug where adding --debug failed the command, and fixed some mixed up params in a function call (yay JS)
N/A
Unit + E2E Tests now pass on the branch (when caught up to `main`).
> chore: get existing e2e tests passing

- packages/amplify-codegen/src/commands/generateStatementsAndType.js
- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/src/commands/types.js
- packages/amplify-codegen/src/utils/getAppSyncAPIInfoFromProject.js
Add a few missing awaits (yay javascript)
N/A
Verified manually per test cases, existing units pass.
> noinit codegen from graphqlconfig

- .codebuild/e2e_workflow.yml
- packages/amplify-codegen-e2e-core/src/categories/codegen.ts
- packages/amplify-codegen-e2e-tests/schemas/sdl/schema.graphql
- packages/amplify-codegen-e2e-tests/schemas/sdl/schema.json
- packages/amplify-codegen-e2e-tests/src/__tests__/add-codegen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/uninitialized-project-codegen-js.test.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/add-codegen.ts
- packages/amplify-codegen/commands/codegen/add.js
- packages/amplify-codegen/package.json
- packages/amplify-codegen/src/commands/add.js
- packages/amplify-codegen/src/commands/generateStatementsAndType.js
- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/src/commands/types.js
- packages/amplify-codegen/src/constants.js
- packages/amplify-codegen/src/utils/downloadIntrospectionSchema.js
- packages/amplify-codegen/src/utils/ensureIntrospectionSchema.js
- packages/amplify-codegen/src/utils/getAppSyncAPIInfoFromProject.js
- packages/amplify-codegen/src/utils/index.js
- packages/amplify-codegen/tests/cli/add.test.js
- packages/amplify-codegen/tests/commands/__snapshots__/add.test.js.snap
- packages/amplify-codegen/tests/commands/add.test.js
Merge in the `noinit-codegen` branch, which will allow customers to execute codegen commands in the amplify cli without any amplify project initialized locally.
N/A
Unit + E2E Tests, Exploratory Testing per a documented test plan.
> feat: support running codegen without an initialized amplify backend set up locally.

- packages/appsync-modelgen-plugin/package.json
- packages/graphql-types-generator/package.json
- yarn.lock
We incorrectly rely on some `types` packages at runtime, this pollutes the runtime a bit. Moving them into devDeps.
N/A
Build + Test Passes
> fix: move types from runtime deps to dev deps

- packages/graphql-generator/API.md
- packages/graphql-generator/src/models.ts
- packages/graphql-generator/src/typescript.ts
useExperimentalPipelinedTranformer -> useExperimentalPipelinedTransformer (missing s in Transformer)
> fix: typo in graphql-generator arg

- packages/amplify-codegen/src/commands/types.js
- packages/amplify-codegen/tests/commands/types.test.js
Type generation for Swift is always generating multiple files. Additionally the when generating multiple files the filename generated is incorrect.
Fallback to old type generation if generating to multiple files. When using the GraphQL generator directly the filenames will still be incorrect.
https://github.com/aws-amplify/amplify-codegen/issues/711
* unit testing
* Manual testing
> fix: swift file names

- packages/amplify-codegen/src/commands/types.js
- packages/amplify-codegen/tests/commands/types.test.js
- packages/appsync-modelgen-plugin/package.json
- packages/graphql-generator/API.md
- packages/graphql-generator/src/models.ts
- packages/graphql-generator/src/typescript.ts
- packages/graphql-types-generator/package.json
- yarn.lock
> Release swift mult files fix

- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/src/commands/types.js
- packages/amplify-codegen/src/utils/getRelativeTypesPath.js
- packages/amplify-codegen/src/utils/index.js
- packages/amplify-codegen/tests/commands/statements.test.js
- packages/amplify-codegen/tests/utils/getRelativeTypesPath.test.js
The relative types path is incorrect when the types file is in the same directory as the GraphQL documents.
The path does not include a prefixed `./`. This causes JS look for a non-relative import.
Resolves: https://github.com/aws-amplify/amplify-codegen/issues/710
* Unit testing
* Manual testing
> fix: relative types path in same dir as documents

- packages/amplify-codegen/src/commands/statements.js
- packages/amplify-codegen/src/utils/getRelativeTypesPath.js
- packages/amplify-codegen/src/utils/index.js
- packages/amplify-codegen/tests/commands/statements.test.js
- packages/amplify-codegen/tests/utils/getRelativeTypesPath.test.js
> Release fix: relative types path in same dir as documents (#714)

- packages/amplify-codegen/src/commands/types.js
- packages/amplify-codegen/tests/commands/types.test.js
- packages/graphql-generator/API.md
- packages/graphql-generator/src/__tests__/__snapshots__/types.test.ts.snap
- packages/graphql-generator/src/__tests__/types.test.ts
- packages/graphql-generator/src/types.ts
- packages/graphql-generator/src/typescript.ts
- packages/graphql-types-generator/API.md
- packages/graphql-types-generator/src/generate.ts
Generate multiple Swift type files. The separate files are for each GraphQL statement file. The multiple type files need the names of the GraphQL statements files in order to generate with the correct names.
This leaves us a few options for the queries arg.
1. `[fileContents: string, filename: string][]`
2. `Source[]` (from `graphql` package).
3. Type union of the current type (string) and one of the two above options.
I chose `string | Source[]` for this PR, but I don't have strong feelings on the end direction.
https://github.com/aws-amplify/amplify-codegen/issues/711
* Unit tests
* Manual tests
> fix: generate multiple swift files

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-typescript-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-typescript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
Set correct type for array of enum. See https://github.com/aws-amplify/amplify-codegen/issues/551 for details.
Resolves: https://github.com/aws-amplify/amplify-codegen/issues/551
Unit testing.
> fix: set correct type for array of enum

- packages/amplify-codegen/tests/commands/mock-fs-setup.js
- packages/amplify-codegen/tests/commands/types-mock-fs.test.js
Add a mock FS test for the multiple Swift type file case.
https://github.com/aws-amplify/amplify-codegen/issues/711
* unit test
> test: add mock fs multiple swift file test

- packages/amplify-codegen/src/utils/getRelativeTypesPath.js
- packages/graphql-generator/src/__tests__/utils/GraphQLStatementsFormatter.test.ts
- packages/graphql-generator/src/__tests__/utils/__snapshots__/GraphQLStatementsFormatter.test.ts.snap
- packages/graphql-generator/src/utils/GraphQLStatementsFormatter.ts
Alternative to https://github.com/aws-amplify/amplify-codegen/pull/727
See https://github.com/aws-amplify/amplify-cli/issues/13289 for details. `path.relative` behaves differently on windows. https://nodejs.org/api/path.html#pathrelativefrom-to
This results in the generated path being invalid syntax in TypeScript/JavaScript.
This change replaces the windows path separator (`path.win32.sep`) with the posix path separator (`path.posix.sep`).
https://github.com/aws-amplify/amplify-cli/issues/13289
* Unit tests
* Need to test on window machine
> fix: ensure posix path sep is used

- .eslintrc.js
- packages/amplify-codegen/package.json
- packages/appsync-modelgen-plugin/package.json
- packages/graphql-types-generator/fixtures/.eslintrc.js
- packages/graphql-types-generator/package.json
- yarn.lock
Removing fixtures from our eslint rules, which were causing us to unnecessarily depend on aws-sdk, amplify js libs, and something else.
I also refreshed the yarn.lock file.
N/A
Unit + E2E Tests
> fix: remove unnecessary deps, including fixture dependencies

- packages/amplify-codegen/src/commands/models.js
- packages/appsync-modelgen-plugin/API.md
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-api-lazyload-css-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-api-lazyload-css-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/configs/java-config.ts
- packages/appsync-modelgen-plugin/src/languages/java-declaration-block.ts
- packages/appsync-modelgen-plugin/src/preset.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
- packages/graphql-generator/API.md
- packages/graphql-generator/src/__tests__/__snapshots__/models.test.ts.snap
- packages/graphql-generator/src/models.ts
- packages/graphql-generator/src/typescript.ts
> Release Codegen

- packages/graphql-types-generator/src/typescript/codeGeneration.ts
- packages/graphql-types-generator/test/typescript/__snapshots__/codeGeneration.js.snap
With the v6 JS library, we now add metadata to queries which reference generated types.
I'm not sure I like this approach, since it generates unnecessary types (instead of just inlining an empty object in the `mutations/subscriptions/queries` files).
https://github.com/aws-amplify/amplify-codegen/issues/736
Unit tests, need to validate in a test app, and run e2e's.
> chore: generate empty types so v6 js types work

- packages/graphql-types-generator/src/typescript/codeGeneration.ts
- packages/graphql-types-generator/test/typescript/__snapshots__/codeGeneration.js.snap
* [chore: generate empty types so v6 js types work (](https://github.com/aws-amplify/amplify-codegen/pull/739/commits/f3e0c45e4989aab8dbbfd617d3c31b5d63a3fbbe)https://github.com/aws-amplify/amplify-codegen/pull/737[)](https://github.com/aws-amplify/amplify-codegen/pull/739/commits/f3e0c45e4989aab8dbbfd617d3c31b5d63a3fbbe)
> Release generate empty types so v6 js types work

- packages/graphql-generator/src/__tests__/utils/GraphQLStatementsFormatter.test.ts
- packages/graphql-generator/src/__tests__/utils/__snapshots__/GraphQLStatementsFormatter.test.ts.snap
- packages/graphql-generator/src/utils/GraphQLStatementsFormatter.ts
Correctly remove file extensions on types import path. See https://github.com/aws-amplify/amplify-codegen/issues/741 for details.
Resolves: https://github.com/aws-amplify/amplify-codegen/issues/741
* Unit testing
> fix: correctly remove file extension on types import path

- packages/amplify-codegen-e2e-core/src/utils/graphql-config-helper.ts
- packages/amplify-codegen/src/commands/add.js
- For non-iOS frontends, the excludes is having an `undefined` value which is eventually failing the `add codegen` workflow. This filters any such values before setting them.
- Updated expected addition to `excludes` entry for iOS e2e tests.
E2Es now pass post fixes
> fix: add codegen for non-ios frontends; updated e2e test for iOS frontend

- .codebuild/e2e_workflow.yml
- packages/amplify-codegen-e2e-core/src/categories/api.ts
- packages/amplify-codegen-e2e-core/src/init/initProjectHelper.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/build-app-android.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/build-app-swift.test.ts
- packages/amplify-codegen-e2e-tests/src/__tests__/build-app-ts.test.ts
- packages/amplify-codegen-e2e-tests/test-apps/ts/.eslintignore
- packages/amplify-codegen-e2e-tests/test-apps/ts/package.json
- packages/amplify-codegen-e2e-tests/test-apps/ts/src/App.tsx
- scripts/split-e2e-tests.ts
Test building an app after generating graphql statements and types.
N/A
Run the tests: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-codegen-e2e-workflow/batch/amplify-codegen-e2e-workflow:0a304923-d204-44dd-9a2c-42e65de590d2?region=us-east-1
> test: build type and graphql statement generation

- .eslintrc.js
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen-e2e-tests/src/__tests__/build-app-swift.test.ts
- yarn.lock
I keep leaving a `test.only` in a test file that is then caught in code review. This adds the test files to eslint and uses the jest preset.
`test.only` will now error on the `jest/no-focused-tests` rule.
There are a few other rules that the tests are failing. I fixed a couple (missing comma and missing graphql dev dep), but left the rest as warnings to fix later.
N/A
N/A
Add a `.only` to one of the tests and:
```
yarn lint
```
> style: run eslint on test files

- dependency_licenses.txt
- package.json
- yarn.lock
also fix dependabot alert for semver
Remove prettier-eslint because it is not used. This fixes a dependabot alert on semver.
N/A
N/A
N/A
> chore: remove prettier-eslint

- packages/appsync-modelgen-plugin/API.md
- packages/appsync-modelgen-plugin/schemas/introspection/1/ModelIntrospectionSchema.json
- packages/appsync-modelgen-plugin/src/__tests__/utils/process-index.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/interfaces/introspection/model-schema.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-model-introspection-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Added support for custom queries/mutations/subscriptions in the generated model introspection schema. The metadata contains field name, field type and arguments. 
Unit & e2e tests
`amplify-dev codegen model-introspection --output-dir .`
> feat(introspection): add metadata for custom GraphQL operations

- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
This PR addresses the omission of `@auth` directive attributes in the generated schema for `@manyToMany` relations, specifically impacting how Datastore performs calls to the joint tables. By ensuring accurate propagation and merging of the `@auth` directives and their rules to the joint table model, this PR facilitates correct authorization information being available for Datastore operations on the joint tables.
https://github.com/aws-amplify/amplify-codegen/issues/473
- Unit tests
- Test in sample app using amplify-dev
> Fix: many to many auth

- shared-scripts.sh
Added verdaccio cache load step in windows e2e setup
Check the codebuild console and examine the installing CLI log for the installed version of `amplify-codegen`. The newly published version from verdaccio proxy is used instead of the one from npm registry.
```
Loading cache folder from s3://****/verdaccio-cache
Loading cache for Windows
Done loading cache folder verdaccio-cache
using Amplify CLI version: 12.10.0
--
| +-- @aws-amplify/amplify-category-api@5.9.3
| +-- amplify-codegen@4.7.4
```
> fix: windows CI not catching latest repo change

- .codebuild/e2e_workflow.yml
- packages/amplify-codegen-e2e-core/src/utils/sdk-calls.ts
- packages/amplify-codegen-e2e-tests/schemas/admin-modelgen.graphql
- packages/amplify-codegen-e2e-tests/src/__tests__/push-codegen-admin-modelgen.test.ts
- packages/amplify-codegen-e2e-tests/src/cleanup-e2e-resources.ts
- packages/amplify-codegen-e2e-tests/src/codegen-tests-base/push-codegen.ts
- packages/appsync-modelgen-plugin/API.md
- packages/appsync-modelgen-plugin/schemas/introspection/1/ModelIntrospectionSchema.json
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-visitor.test.ts
- packages/appsync-modelgen-plugin/src/interfaces/introspection/model-schema.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-model-introspection-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
The `input`, `union` and `interface` types are correctly processed by the base visitor when it is defined in the GQL schema. The union and interface IR, however, will not be processed into the output of MIS 
The type of model schema is changed
```TypeScript
export type ModelIntrospectionSchema = {
version: 1;
models: SchemaModels;
nonModels: SchemaNonModels;
enums: SchemaEnums;
queries?: SchemaQueries;
mutations?: SchemaMutations;
subscriptions?: SchemaSubscriptions;
// new root level optional attribute
inputs?: SchemaInputs 
};
// New type definitions
export type SchemaInputs = Record<string, Input>;
export type Input = {
name: string;
arguments: Arguments
}
// Fine-grained field type
export type ScalarType = 'ID'
| 'String'
| 'Int'
| 'Float'
| 'AWSDate'
| 'AWSTime'
| 'AWSDateTime'
| …
```
> fix: process input object, union and interface metadata in model introspection schema codegen

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-swift-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
* do not remove belongsTo target names when using references on native
N/A
N/A
* Unit tests
> fix: do not remove belongsTo target names when using references

- packages/graphql-generator/API.md
- packages/graphql-generator/src/__tests__/__snapshots__/models.test.ts.snap
- packages/graphql-generator/src/models.ts
- packages/graphql-generator/src/typescript.ts
BREAKING CHANGE: use transformer version 2 by default in graphql-generator package
`transformerVersion` parameter had the wrong type. It was boolean instead of number. With the current default `true` the transformer version 1 was being used by default.
This means that gen 2 model generation is using has `transformerVersion` set to 1. Gen 1 is still using the cli.json feature flag which has explicitly set the version.
The parameter is used here: 
1. https://github.com/aws-amplify/amplify-codegen/blob/9f559413621dcc4a4a5158a129e575371c6d8c35/packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts#L394
2. https://github.com/aws-amplify/amplify-codegen/blob/9f559413621dcc4a4a5158a129e575371c6d8c35/packages/appsync-modelgen-plugin/src/preset.ts#L325
This is a breaking change for …
> fix!: use transformer version 2 by default

- packages/appsync-modelgen-plugin/API.md
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/gqlv2-regression-tests/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
- packages/graphql-generator/src/__tests__/__snapshots__/models.test.ts.snap
Flatens the nested data structure of `serializedData` found in the `.fromJson()` method on codegen models. This PR is to be paired with changes in [amplify-flutter#4665](https://github.com/aws-amplify/amplify-flutter/pull/4665)
https://github.com/aws-amplify/amplify-flutter/issues/816
Change were validated via: 
1. amplify-codegen tests
2. amplify-flutter api category unit & integ tests 
3. amplify-flutter datastore category unit & integ tests 
4. Manual testing within both categories on ios & android devices
> chore(amplify-codegen): dart api model .fromJson() refactor

- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
Adds todo to clean up Dart codegen in next major version bump
Adds a Todo comment to clean up deprecated Dart codgen for `Model.getId()` in the next major version. Amplify Flutter V2 will no longer use this API.  
none
none
It's just a comment
> style(amplify-codegen): adds a todo comment

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/utils/process-belongs-to.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections-v2.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections.ts
- packages/appsync-modelgen-plugin/src/utils/process-has-many.ts
- packages/appsync-modelgen-plugin/src/utils/process-has-one.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
* remove `respectReferences` and enable references for all platforms
* use the connected field instead of associatedWithFields on native for references
Example:
```
type Primary @model {                                                                                                                
tenantId: ID! @primaryKey(sortKeyFields: ["instanceId", "recordId"])                                                               
instanceId: ID!                                                                                                                    
recordId: ID!                                                                                                                      
content: String …
```
> feat: use a different associated field for references on native

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-java-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-java-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
The java builder steps did not respect `handleListNullabilityTransparently`. This was an issue because the code generation for the builder step interfaces did respect `handleListNullabilityTransparently`. This would sometimes result in a case where a builder step was created but the interface for the builder step was not created.
For the following model when `handleListNullabilityTransparently` is true, the builder step would be crated but the interface would not be created resulting in compilation error.
```graphql
type Foo @model {
items: [String!]
}
```
Interface creation:
https://github.com/aws-amplify/amplify-codegen/blob/a909ff333af7513c6babfa8cf5f6cfce57e854e5/packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts#L412-L419
Builder step creation: …
> fix: java builder steps to respect handleListNullabilityTransparently

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-swift-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
* add missing closing parens on swift hasMany when using references.
N/A
N/A
* Unit tests
* E2E tests
> fix: add missing closing parens on swift hasMany

- packages/amplify-codegen-e2e-tests/package.json
- yarn.lock
* upgrade test schema library
A major version bump in the test schema library caused the E2E tests to not update with the new schemas.
https://github.com/aws-amplify/amplify-codegen/pull/835 should have been caught by the tests, but the schema was not included in the tests.
N/A
N/A
* E2E tests
> chore: upgrade test schema library

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-dart-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
Added the dropped Flutter V1 `Model.fromJson()` decoding logic back to non-model embeds. Customer observed embedded non-model types not populating values after requests were made. This adds a fallback to previous logic.
https://github.com/aws-amplify/amplify-flutter/issues/4872
Validated decoding against this schema in both Flutter V1 and V2. 
```graphql
type MyModel @model @auth(rules: [{ allow: owner }]) {
id: ID!
owner: String
token: Token
tokens: [Token]
}
type Token {
externalId: String!
value: String!
}
```
> fix(amplify-codegen): fix for non-model decoding in flutter v1

- .codebuild/deprecate.yml
- .codebuild/deprecate_workflow.yml
- .codebuild/install_linux.yml
- .codebuild/scripts/local_publish_helpers.sh
- .gitignore
- .prettierignore
- package.json
- scripts/cloud-release.sh
- scripts/cloud-utils.sh
- scripts/components/dist_tag_mover.ts
- scripts/components/git_client.ts
- scripts/components/npm_client.ts
- scripts/components/release_deprecator.ts
- scripts/components/release_tag_to_name_and_version.ts
- scripts/deprecate_release.ts
- scripts/postinstall.sh
- shared-scripts.sh
Copy workflow from https://github.com/aws-amplify/amplify-category-api/pull/2532
Dry run in personal account.
```
yarn trigger-deprecate-release "contains regression" cbbb1d39c326c4097d9ff06556d6ddd337662d22 false
```
```
Moving dist tag "latest" to release tag @aws-amplify/appsync-modelgen-plugin@2.12.0
--
54 | +latest: @aws-amplify/appsync-modelgen-plugin@2.12.0
55 | Done!
56 |  
57 | Moving dist tag "latest" to release tag @aws-amplify/graphql-generator@0.4.1
58 | +latest: @aws-amplify/graphql-generator@0.4.1
59 | Done!
60 |  
61 | Moving dist tag "latest" to release tag amplify-codegen@4.9.1
62 | +latest: amplify-codegen@4.9.1
63 | Done!
64 |  
65 | Deprecating package version @aws-amplify/appsync-modelgen-plugin@2.12.1
66 | Done!
67 |  
68 | Deprecating package version …
```
> ci: add deprecate workflow

- package.json
- scripts/create-private-package-manifest.sh
- shared-scripts.sh
Move the `postinstall` script to be run as part of deprecate workflow where it is needed.
This was causing issues in windows environments where the script is not being executed as part of `postinstall` action.
Verified that the contents of the script or execute permissions aren't the issue.
> chore: fix windows build issue

- .github/PULL_REQUEST_TEMPLATE.md
Add a checklist step to verify the supported graphql types to the PR template.
NA
NA
NA
> chore: add checklist to verify the supported graphql types

- .github/ISSUE_TEMPLATE/1.gen2_bug_report.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- dependency_licenses.txt
- packages/appsync-modelgen-plugin/src/interfaces/introspection/model-schema.ts
- yarn.lock
> chore: prep release

- packages/amplify-codegen-e2e-tests/src/__tests__/backends/graphql-generator-gen2/resource.ts
It is not possible to use `a.ref` in a custom query/mutation currently. Previously the `enum` would need to be defined twice (once as the top-level enum type and then in the custom query/mutation).
```typescript
EchoQueryStatus: a.enum([
'PROGRESS',
'COMPLETED',
]),
// Custom query
echoQuery: a
.query()
.arguments({
status: a.enum(['PROGRESS', 'COMPLETED']),
})
```
A change to the data schema builder now auto-creates the top-level enum type. This resulted in duplicate enum definition for `EchoQueryStatus` in our tests.
```graphql
enum EchoQueryStatus {
PROGRESS
COMPLETED
}
enum EchoQueryStatus {
PROGRESS
COMPLETED
}
```
[E2E tests](https://us-east-1.console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/build-batch/amplify-codegen-e2e-workflow:459bcbdf-9e47-485c-a353-f877ec583a43/v …
> test: remove duplicate enum def

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-index.test.ts
- packages/appsync-modelgen-plugin/src/utils/fieldUtils.ts
- packages/appsync-modelgen-plugin/src/utils/process-index.ts
Fixes a bug where multiple indexes on a field is not correctly represented on the generated model introspection schema.
No.
Fixes https://github.com/aws-amplify/amplify-category-api/issues/2815
- Unit tests
- Manual test
> [!NOTE]  
> **Manual testing:** I've tested the fix on a sample Gen2 app using NPM overrides pointing to the local packaged module.
> fix(amplify-codegen): support multiple indexes on the same field in introspection schema

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
CLI v11.0.0 introduced creating the model introspection schema at the end of every amplify push. Some customers using the v1 transformer with `@connection` with DataStore disabled were unable to upgrade to later versions of the CLI and successfully push. The model generation at the end of the push failed with `DataStore does not support 1 to 1 connection with both sides of connection as optional field`. This error is not applicable to customers not using DataStore. This error would also print the case the connection was required on both sides.
This change removes this restriction from customers not using DataStore. 
Currently working (user is not required).
```graphql
type User @model {
id: ID!
}
type Session @model {
id: ID!
sessionUserId: ID!
user: User @connection(fields: …
```
> fix: allow required uni-directional hasOne with @connection when datastore is disabled

- packages/appsync-modelgen-plugin/src/__tests__/utils/process-connections.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/utils/process-connections.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Release https://github.com/aws-amplify/amplify-codegen/pull/888
E2E tests covered in previous PR: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-codegen-e2e-workflow/batch/amplify-codegen-e2e-workflow%3A6e0f2996-f724-4536-8b73-e5dad41d18a0?region=us-east-1
---
> Prep release

- packages/amplify-codegen-e2e-core/src/init/initProjectHelper.ts
- packages/amplify-codegen-e2e-core/src/utils/pinpoint.ts
- packages/amplify-codegen-e2e-tests/src/init-special-cases/index.ts
Adds the missing prompts during `amplify init` that were recently added by CLI team.
Full E2E
> chore: handle Gen1 usage prompt during init

- package.json
- packages/amplify-codegen-e2e-tests/package.json
- yarn.lock
- Consume the latest version of `@aws-amplify/graphql-schema-test-library` that is published from [API repo main branch](https://github.com/aws-amplify/amplify-category-api/blob/main/packages/amplify-graphql-schema-test-library/package.json).
- Upgrade the `cookie` version pulled in transitively from the E2E test package.
CI checks - triggered E2E
> chore: update schema test library version, cookie dep version

- package.json
- packages/amplify-codegen-e2e-core/src/init/initProjectHelper.ts
- packages/amplify-codegen-e2e-core/src/utils/pinpoint.ts
- packages/amplify-codegen-e2e-tests/package.json
- packages/amplify-codegen-e2e-tests/src/init-special-cases/index.ts
- yarn.lock
- Dependabot alert fix for `cookie`
- E2E test fixes
Full E2E run passed - see CI check
> chore: release codegen plugin

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/utils/process-conversation.ts
- Adds missing `owner` field to `Conversation<RouteName>` model.
N/A
N/A
> fix(appsync-modelgen-plugin): add conversation.owner field

- .codebuild/canary_workflow.yml
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/utils/process-conversation.ts
PR to merge main into release branch to initiate a release.
> chore: release codegen

- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/utils/process-conversation.ts
- https://github.com/aws-amplify/amplify-category-api/pull/3023
- https://github.com/aws-amplify/amplify-api-next/pull/395
Conversation routes add several GraphQL types (type, input, enum, interface) to the GraphQL schema. These types are only added if a conversation route is defined via the `@conversation` directive and are conversation route agnostic (only added once per GraphQL schema regardless of the amount of conversation routes).
These types have generic enough names that they can conflict with customer defined types. 
<details>
<summary>GraphQL Types</summary>
```graphql
enum ConversationParticipantRole {
user
assistant
}
interface ConversationMessage {
id: ID!
conversationId: ID!
associatedUserMessageId: ID
role: ConversationParticipantRole
content: [ContentBlock]
aiContext: …
```
> fix(conversation): prefix supporting types with AmplifyAI

- .codebuild/canary_workflow.yml
- .codebuild/run_canary_android_modelgen_e2e_test.yml
- .codebuild/run_canary_e2e_tests.yml
- .codebuild/run_canary_ios_modelgen_e2e_test.yml
- shared-scripts.sh
- Added specific build specifications for iOS, Android, and JS apps in the canary pipeline.
- Introduced the `_emitCodegenCanaryMetric` function in `shared-scripts.sh` to send metric data to CloudWatch.
- Updated the canary workflow to include the appropriate buildspec values for all tests.
> chore: added emit metric function with buildspec for canaries

- .codebuild/canary_workflow.yml
- Updated `build-app-test.ts` to include `DISABLE_ESLINT_PLUGIN: true`.  
- Resolves the `react` version conflict between `eslintrc.js` and `base-config.js`.
- Verified locally by forking release branch and verifying the workflow succeeds.
> chore: disable eslint for build-app test canary

- .github/workflows/build-swift-modelgen.yml
- Updated the `build-swift-modelgen.yml` workflow `runs-on` property.
-  It was previously set to an invalid value, `macos-13-xl`.
- Updated it to the correct value, `macos-13-xlarge`.
- [https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/running-jobs-on-larger-runners?platform=mac#availabl[…]r-runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/running-jobs-on-larger-runners?platform=mac#available-macos-larger-runners)
> fix: updated github workflow runs-on property to x-large runners

- shared-scripts.sh
- The Codegen Canary workflow comprises three distinct test suites:
1. `build-app-ts`
2. `build-app-android`
3. `build-app-swift`
- To improve error detection speed and efficiency, updates to the Canary frequency and alarms were necessary.
- Separating metrics for each test suite facilitates easier troubleshooting during `ALARM` states and helps have fewer data points to consider during each Evaluation period for the workflow.
1. Enhanced `_emitCodegenCanaryMetric` function:
- Added a new `test` dimension to differentiate between test suites.
- The `test` dimension now includes the following values:
- `ts` for TypeScript tests
- `swift` for Swift tests
- `android` for Android tests
- These values correspond directly to their respective `TEST_SUITE` in the `canary_workflow.yml`.
1. …
> chore: update emit metric function to differentiate tests

- .codebuild/run_android_modelgen_e2e_test.yml
The build Android app E2E test is failing because the Corretto pgp key has expired and is not able finish installing with APT. Remove and refetch the key as recommended in https://github.com/corretto/corretto-21/issues/83.
We could also create a new ECR image, but I figured this would be sufficient and less effort.
N/A
N/A
E2E test: https://594813022831-5xzrh3qa.us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-codegen-e2e-workflow/batch/amplify-codegen-e2e-workflow%3A54f8919b-dbb0-4d9b-adca-d5dd3e6621d0?region=us-east-1
This PR only fixes `build_app_android`. The `l_graphql_generator_gen2` and `w_graphql_generator_gen2` will still fail due to a different issue.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> ci: renew corretto pgp key

- .codebuild/run_android_modelgen_e2e_test.yml
This reverts commit 37cbcb09de3702a9e8f4c539b2a60db5b2012d4e.
Revert the change to update the pgp key. The canary is using a new CodeBuild image that already has the updated key. I will follow up this PR with a change to use the canary image for the E2E tests.
---
> Revert "ci: renew corretto pgp key (#925)"

- .codebuild/android_canary_workflow.yml
- .codebuild/canary_workflow_base.yml
- .codebuild/e2e_workflow.yml
- .codebuild/ios_canary_workflow.yml
- .codebuild/run_android_modelgen_e2e_test.yml
- .codebuild/run_canary_android_modelgen_e2e_test.yml
- .codebuild/run_regionalized_android_modelgen_e2e_test.yml
- .codebuild/run_regionalized_ios_modelgen_e2e_test.yml
- .codebuild/run_regionalized_ts_modelgen_e2e_test.yml
- .codebuild/ts_canary_workflow.yml
- package.json
- packages/amplify-codegen-e2e-tests/src/__tests__/build-app-android.test.ts
- packages/amplify-codegen-e2e-tests/src/cleanup-e2e-resources.ts
- scripts/split-canary-tests.ts
- scripts/split-e2e-tests.ts
- scripts/support-test-regions.json
- shared-scripts.sh
Added regionalized `.yml` CodeBuild spec files for three app builds (`ts`, `swift`, `android`) canaries.
These build spec files are auto generated by running `yarn split-canary-tests`, with regions sourced from [Amplify supported regions](https://docs.aws.amazon.com/general/latest/gr/amplify.html).
> feat: add regionalized build spec for three canaries

- .eslintrc.js
- packages/appsync-modelgen-plugin/src/__tests__/visitors/__snapshots__/appsync-model-introspection-visitor.test.ts.snap
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-dart-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-javascript-visitor.test.ts
- packages/appsync-modelgen-plugin/src/__tests__/visitors/appsync-model-introspection-visitor.test.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-dart-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-java-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-javascript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts
- packages/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts
Codegen currently pascal cases enums defined in the GraphQL schema.
Gen 2 doesn't pascal case top-level enums:
```ts
const schema = a.schema({
foo: a.enum(["a1", "b1"]),
});
```
generates:
```gql
enum foo {
a1
b1
}
```
This naming discrepancy hasn't caused problems yet because:
1. Type names for return types aren’t included in GraphQL operations.
2. The only way an enum can be used as an input today is through a generated model query. For example:
```ts
const schema = a.schema({
foo: a.enum(["a1", "b1"]),
Todo: a.model({
status: a.boolean(),
test: a.ref('foo')
}),
});
```
But we create a wrapper input type for all model generated queries. So the actual GraphQL mutation here uses CreateTodoInput + Variables and never mentions the `foo` type.
```js
{
"query": "mutation ($input: …
```
> fix: stop pascal casing enums for MIS

- .codebuild/android_canary_workflow.yml
- .codebuild/e2e_workflow.yml
- .codebuild/ios_canary_workflow.yml
- .codebuild/ts_canary_workflow.yml
- packages/amplify-codegen-e2e-core/src/configure/index.ts
- scripts/e2e-test-regions.json
- scripts/split-canary-tests.ts
- scripts/split-e2e-tests.ts
Fixed possible region discrepancy in `amplify configure` due to mismatch between Amplify CLI command dropdown and test script region list.
Plus, removed `ap-east-1` from E2E regions as there is a known difference between Amplify CLI regions and Amplify supported regions. Customer will still be able to deploy app to `ap-east-1`, but this region is not currently supported via `amplify configure`. Having test running in this region will redirect test back to `us-east-1` and failed the Amplify profile assertion in test setup phase.
CI E2Es
> fix: use correct region in amplify configure

- packages/amplify-codegen-e2e-tests/src/cleanup-e2e-resources.ts
Added additional handling to invalid token scenarios in cleanup scripts, since some child test accounts do not have opt-in region enabled, and will encounter invalid token/client error.
> fix: cleanup detection of regional availability

- .codebuild/build_windows.yml
- packages/amplify-codegen-e2e-tests/src/gen2-codegen-tests-base/commands.ts
- shared-scripts.sh
`l_graphql_generator_gen2` and `w_graphql_generator_gen2` were failing because CodeBuild was using an older Node version. This PR adds logic to install Node 18.20 for both Windows and Linux environments.
After upgrading to Node 18.20, on Windows, the execution of `npx.cmd` was failing with an `EINVAL` error when calling `spawnSync` in the test. This error is due to a recent [Node.js security update (April 10, 2024)](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high). The update enforces that batch files (like `.cmd`) must be run with `shell: true` to prevent potential command injection vulnerabilities. Without this option, Node now errors with …
> fix: add script to use node 18.20

- packages/amplify-codegen-e2e-tests/src/cleanup-e2e-resources.ts
Disabled pagination when fetching all regions from SDK `Account.listRegions`, so all regions will be retrieved from request for cleanup.
> fix: handle pagination when fetching region list in cleanup

- dependency_licenses.txt
- package.json
- yarn.lock
This PR pins @octokit/request-error, @octokit/request, and @octokit/plugin-paginate-rest to patched versions to address the following dependabot alerts relating to @octokit versions:
- https://github.com/aws-amplify/amplify-codegen/security/dependabot/79
- https://github.com/aws-amplify/amplify-codegen/security/dependabot/78
- https://github.com/aws-amplify/amplify-codegen/security/dependabot/77
> choore: pin octokit to secure versions

- dependency_licenses.txt
- package.json
- packages/amplify-codegen-e2e-core/package.json
- packages/amplify-codegen-e2e-tests/package.json
- yarn.lock
Bumped `@aws-amplify/amplify-cli-core` to latest version v4.4.0 to resolve following dependabot alert:
https://github.com/aws-amplify/amplify-codegen/security/dependabot/72
`aws-cdk-lib` is introduced to `yarn.lock` as a transitive dependency of `@aws-amplify/amplify-cli-core`, and bumped to latest version will resolve the issue.
> chore: bump cli core to latest version

- shared-scripts.sh
- Codegen Canary regionalized workflows fail with `npm EIDLETIMEOUT error`
- Adding longer timeouts and retries to avoid timeout error
- Ran a Codebuild job with above changes to verify canary tests pass, runs linked below
- [Android](https://594813022831-qxxvc3uq.us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-codegen-android-app-build-canary-workflow/batch/amplify-codegen-android-app-build-canary-workflow%3A3bfe1ff9-a5b2-402d-b2be-2c3f085fb69b?region=us-east-1)
- [Ios](https://594813022831-qxxvc3uq.us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-codegen-ios-app-build-canary-workflow/batch/amplify-codegen-ios-app-build-canary-workflow%3A20746ad4-a109-47ea-bb47-5364f3e96559?region=us-east-1)
- …
> chore: add timeout before installing cli from local registry

- shared-scripts.sh
- yarn.lock
- Codegen Canary error `npm EIDLETIMEOUT` fix
- executed `yarn cloud-e2e` [test run](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/594813022831/projects/amplify-codegen-e2e-workflow/batch/amplify-codegen-e2e-workflow:99f8ab33-a5a7-42c6-954a-5d60605ed4f3?region=us-east-1)
> chore: Release PR

- .codebuild/scripts/run-ios-modelgen-e2e-test.sh
Increase iOS codegen canary timeout. The canaries are reaching the timeout more frequently starting this afternoon. It is not clear what the issue is yet, but this will stop the bleeding.
---
> test: increase ios codegen canary timeout

- package.json
- packages/amplify-codegen-e2e-core/package.json
- packages/amplify-codegen-e2e-tests/package.json
- yarn.lock
Fixes: https://github.com/aws-amplify/amplify-codegen/security/dependabot/85
> chore: upgrade aws-cdk and amplify-core versions

- .github/workflows/build-swift-modelgen.yml
Attempt to fix https://github.com/aws-amplify/amplify-codegen/blob/main/.github/workflows/build-swift-modelgen.yml, switch macos runner and Xcode version to minimum required Xcode version for Amplify Swift.
> chore: use newer macos runner
